version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16  # Образ сразу с вектором
    container_name: eb1a_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Situation00!
      POSTGRES_DB: eb1abot
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: